// Türkiye'deki il ve ilçeler
export const turkiyeIlIlce = {
    provinces: [
        { id: 1, name: "Adana", slug: "adana" },
        { id: 2, name: "Adıyaman", slug: "adiyaman" },
        { id: 3, name: "Afyonkarahisar", slug: "afyonkarahisar" },
        { id: 4, name: "Ağrı", slug: "agrı" },
        { id: 68, name: "Aksaray", slug: "aksaray" },
        { id: 5, name: "Amasya", slug: "amasya" },
        { id: 6, name: "Ankara", slug: "ankara" },
        { id: 7, name: "Antalya", slug: "antalya" },
        { id: 75, name: "Ardahan", slug: "ardahan" },
        { id: 8, name: "Artvin", slug: "artvin" },
        { id: 9, name: "Aydın", slug: "aydin" },
        { id: 10, name: "Balıkesir", slug: "balikesir" },
        { id: 74, name: "Bartın", slug: "bartin" },
        { id: 72, name: "Batman", slug: "batman" },
        { id: 69, name: "Bayburt", slug: "bayburt" },
        { id: 11, name: "Bilecik", slug: "bilecik" },
        { id: 12, name: "Bingöl", slug: "bingol" },
        { id: 13, name: "Bitlis", slug: "bitlis" },
        { id: 14, name: "Bolu", slug: "bolu" },
        { id: 15, name: "Burdur", slug: "burdur" },
        { id: 16, name: "Bursa", slug: "bursa" },
        { id: 17, name: "Çanakkale", slug: "canakkale" },
        { id: 18, name: "Çankırı", slug: "cankiri" },
        { id: 19, name: "Çorum", slug: "corum" },
        { id: 20, name: "Denizli", slug: "denizli" },
        { id: 21, name: "Diyarbakır", slug: "diyarbakir" },
        { id: 81, name: "Düzce", slug: "duzce" },
        { id: 22, name: "Edirne", slug: "edirne" },
        { id: 23, name: "Elazığ", slug: "elazig" },
        { id: 24, name: "Erzincan", slug: "erzincan" },
        { id: 25, name: "Erzurum", slug: "erzurum" },
        { id: 26, name: "Eskişehir", slug: "eskisehir" },
        { id: 27, name: "Gaziantep", slug: "gaziantep" },
        { id: 28, name: "Giresun", slug: "giresun" },
        { id: 29, name: "Gümüşhane", slug: "gumushhane" },
        { id: 30, name: "Hakkari", slug: "hakkari" },
        { id: 31, name: "Hatay", slug: "hatay" },
        { id: 76, name: "Iğdır", slug: "igdir" },
        { id: 32, name: "Isparta", slug: "isparta" },
        { id: 34, name: "İstanbul", slug: "istanbul" },
        { id: 35, name: "İzmir", slug: "izmir" },
        { id: 46, name: "Kahramanmaraş", slug: "kahramanmaras" },
        { id: 78, name: "Karabük", slug: "karabuk" },
        { id: 70, name: "Karaman", slug: "karaman" },
        { id: 36, name: "Kars", slug: "kars" },
        { id: 37, name: "Kastamonu", slug: "kastamonu" },
        { id: 38, name: "Kayseri", slug: "kayseri" },
        { id: 71, name: "Kırıkkale", slug: "kirikkale" },
        { id: 39, name: "Kırklareli", slug: "kirklareli" },
        { id: 40, name: "Kırşehir", slug: "kirsehir" },
        { id: 79, name: "Kilis", slug: "kilis" },
        { id: 41, name: "Kocaeli", slug: "kocaeli" },
        { id: 42, name: "Konya", slug: "konya" },
        { id: 43, name: "Kütahya", slug: "kutahya" },
        { id: 44, name: "Malatya", slug: "malatya" },
        { id: 45, name: "Manisa", slug: "manisa" },
        { id: 47, name: "Mardin", slug: "mardin" },
        { id: 33, name: "Mersin", slug: "mersin" },
        { id: 48, name: "Muğla", slug: "mugla" },
        { id: 49, name: "Muş", slug: "mus" },
        { id: 50, name: "Nevşehir", slug: "nevsehir" },
        { id: 51, name: "Niğde", slug: "nigde" },
        { id: 52, name: "Ordu", slug: "ordu" },
        { id: 80, name: "Osmaniye", slug: "osmaniye" },
        { id: 53, name: "Rize", slug: "rize" },
        { id: 54, name: "Sakarya", slug: "sakarya" },
        { id: 55, name: "Samsun", slug: "samsun" },
        { id: 56, name: "Siirt", slug: "siirt" },
        { id: 57, name: "Sinop", slug: "sinop" },
        { id: 58, name: "Sivas", slug: "sivas" },
        { id: 63, name: "Şanlıurfa", slug: "sanlıurfa" },
        { id: 73, name: "Şırnak", slug: "sırnak" },
        { id: 59, name: "Tekirdağ", slug: "tekirdag" },
        { id: 60, name: "Tokat", slug: "tokat" },
        { id: 61, name: "Trabzon", slug: "trabzon" },
        { id: 62, name: "Tunceli", slug: "tunceli" },
        { id: 64, name: "Uşak", slug: "usak" },
        { id: 65, name: "Van", slug: "van" },
        { id: 77, name: "Yalova", slug: "yalova" },
        { id: 66, name: "Yozgat", slug: "yozgat" },
        { id: 67, name: "Zonguldak", slug: "zonguldak" }
    ],
    districts: [
        // Adana (1)
        { id: 1, province_id: 1, name: "Aladağ", slug: "aladag" },
        { id: 2, province_id: 1, name: "Ceyhan", slug: "ceyhan" },
        { id: 3, province_id: 1, name: "Çukurova", slug: "cukurova" },
        { id: 4, province_id: 1, name: "Feke", slug: "feke" },
        { id: 5, province_id: 1, name: "İmamoğlu", slug: "imamoglu" },
        { id: 6, province_id: 1, name: "Karaisalı", slug: "karaisali" },
        { id: 7, province_id: 1, name: "Karataş", slug: "karatas" },
        { id: 8, province_id: 1, name: "Kozan", slug: "kozan" },
        { id: 9, province_id: 1, name: "Pozantı", slug: "pozanti" },
        { id: 10, province_id: 1, name: "Saimbeyli", slug: "saimbeyli" },
        { id: 11, province_id: 1, name: "Sarıçam", slug: "saricam" },
        { id: 12, province_id: 1, name: "Seyhan", slug: "seyhan" },
        { id: 13, province_id: 1, name: "Tufanbeyli", slug: "tufanbeyli" },
        { id: 14, province_id: 1, name: "Yumurtalık", slug: "yumurtalik" },
        { id: 15, province_id: 1, name: "Yüreğir", slug: "yuregir" },

        // Adıyaman (2)
        { id: 16, province_id: 2, name: "Besni", slug: "besni" },
        { id: 17, province_id: 2, name: "Çelikhan", slug: "celikhan" },
        { id: 18, province_id: 2, name: "Gerger", slug: "gerger" },
        { id: 19, province_id: 2, name: "Gölbaşı", slug: "golbası" },
        { id: 20, province_id: 2, name: "Kahta", slug: "kahta" },
        { id: 21, province_id: 2, name: "Merkez", slug: "merkez" },
        { id: 22, province_id: 2, name: "Samsat", slug: "samsat" },
        { id: 23, province_id: 2, name: "Sincik", slug: "sincik" },
        { id: 24, province_id: 2, name: "Tut", slug: "tut" },

        // Afyonkarahisar (3)
        { id: 25, province_id: 3, name: "Başmakçı", slug: "basmakci" },
        { id: 26, province_id: 3, name: "Bayat", slug: "bayat" },
        { id: 27, province_id: 3, name: "Bolvadin", slug: "bolvadin" },
        { id: 28, province_id: 3, name: "Çay", slug: "cay" },
        { id: 29, province_id: 3, name: "Çobanlar", slug: "cobanlar" },
        { id: 30, province_id: 3, name: "Dazkırı", slug: "dazkiri" },
        { id: 31, province_id: 3, name: "Dinar", slug: "dinar" },
        { id: 32, province_id: 3, name: "Emirdağ", slug: "emirdag" },
        { id: 33, province_id: 3, name: "Evciler", slug: "evciler" },
        { id: 34, province_id: 3, name: "Hocalar", slug: "hocalar" },
        { id: 35, province_id: 3, name: "İhsaniye", slug: "ihsaniye" },
        { id: 36, province_id: 3, name: "İscehisar", slug: "iscehisar" },
        { id: 37, province_id: 3, name: "Kızılören", slug: "kiziloren" },
        { id: 38, province_id: 3, name: "Merkez", slug: "merkez" },
        { id: 39, province_id: 3, name: "Sandıklı", slug: "sandikli" },
        { id: 40, province_id: 3, name: "Sinanpaşa", slug: "sinanpasa" },
        { id: 41, province_id: 3, name: "Sultandağı", slug: "sultandagi" },
        { id: 42, province_id: 3, name: "Şuhut", slug: "suhut" },

        // Ağrı (4)
        { id: 43, province_id: 4, name: "Diyadin", slug: "diyadin" },
        { id: 44, province_id: 4, name: "Doğubayazıt", slug: "dogubayazit" },
        { id: 45, province_id: 4, name: "Eleşkirt", slug: "eleskirt" },
        { id: 46, province_id: 4, name: "Hamur", slug: "hamur" },
        { id: 47, province_id: 4, name: "Merkez", slug: "merkez" },
        { id: 48, province_id: 4, name: "Patnos", slug: "patnos" },
        { id: 49, province_id: 4, name: "Taşlıçay", slug: "taslicay" },
        { id: 50, province_id: 4, name: "Tutak", slug: "tutak" },

        // Aksaray (68)
        { id: 51, province_id: 68, name: "Ağaçören", slug: "agacoren" },
        { id: 52, province_id: 68, name: "Eskil", slug: "eskil" },
        { id: 53, province_id: 68, name: "Gülağaç", slug: "gulagac" },
        { id: 54, province_id: 68, name: "Güzelyurt", slug: "guzeluyurt" },
        { id: 55, province_id: 68, name: "Merkez", slug: "merkez" },
        { id: 56, province_id: 68, name: "Ortaköy", slug: "ortakoy" },
        { id: 57, province_id: 68, name: "Sarıyahşi", slug: "sariyahsi" },
        { id: 58, province_id: 68, name: "Sultanhanı", slug: "sultanhani" },

        // Amasya (5)
        { id: 59, province_id: 5, name: "Göynücek", slug: "goyuncek" },
        { id: 60, province_id: 5, name: "Gümüşhacıköy", slug: "gumushacikoy" },
        { id: 61, province_id: 5, name: "Hamamözü", slug: "hamamozu" },
        { id: 62, province_id: 5, name: "Merkez", slug: "merkez" },
        { id: 63, province_id: 5, name: "Merzifon", slug: "merzifon" },
        { id: 64, province_id: 5, name: "Suluova", slug: "suluova" },
        { id: 65, province_id: 5, name: "Taşova", slug: "tasova" },

        // Ankara (6)
        { id: 66, province_id: 6, name: "Akyurt", slug: "akyurt" },
        { id: 67, province_id: 6, name: "Altındağ", slug: "altindag" },
        { id: 68, province_id: 6, name: "Ayaş", slug: "ayas" },
        { id: 69, province_id: 6, name: "Bala", slug: "bala" },
        { id: 70, province_id: 6, name: "Beypazarı", slug: "beypazari" },
        { id: 71, province_id: 6, name: "Çamlıdere", slug: "camlidere" },
        { id: 72, province_id: 6, name: "Çankaya", slug: "cankaya" },
        { id: 73, province_id: 6, name: "Çubuk", slug: "cubuk" },
        { id: 74, province_id: 6, name: "Elmadağ", slug: "elmada" },
        { id: 75, province_id: 6, name: "Etimesgut", slug: "etimesgut" },
        { id: 76, province_id: 6, name: "Evren", slug: "evren" },
        { id: 77, province_id: 6, name: "Gölbaşı", slug: "golbası" },
        { id: 78, province_id: 6, name: "Güdül", slug: "gudul" },
        { id: 79, province_id: 6, name: "Haymana", slug: "haymana" },
        { id: 80, province_id: 6, name: "Kahramankazan", slug: "kahramankazan" },
        { id: 81, province_id: 6, name: "Kalecik", slug: "kalecik" },
        { id: 82, province_id: 6, name: "Keçiören", slug: "kecioren" },
        { id: 83, province_id: 6, name: "Kızılcahamam", slug: "kizilcahamam" },
        { id: 84, province_id: 6, name: "Mamak", slug: "mamak" },
        { id: 85, province_id: 6, name: "Nallıhan", slug: "nallihan" },
        { id: 86, province_id: 6, name: "Polatlı", slug: "polatli" },
        { id: 87, province_id: 6, name: "Pursaklar", slug: "pursaklar" },
        { id: 88, province_id: 6, name: "Sincan", slug: "sincan" },
        { id: 89, province_id: 6, name: "Şereflikoçhisar", slug: "sereflikochisar" },
        { id: 90, province_id: 6, name: "Yenimahalle", slug: "yenimahalle" },

        // Antalya (7)
        { id: 91, province_id: 7, name: "Akseki", slug: "akseki" },
        { id: 92, province_id: 7, name: "Aksu", slug: "aksu" },
        { id: 93, province_id: 7, name: "Alanya", slug: "alanya" },
        { id: 94, province_id: 7, name: "Demre", slug: "demre" },
        { id: 95, province_id: 7, name: "Döşemealtı", slug: "dusemealti" },
        { id: 96, province_id: 7, name: "Elmalı", slug: "elmali" },
        { id: 97, province_id: 7, name: "Finike", slug: "finike" },
        { id: 98, province_id: 7, name: "Gazipaşa", slug: "gazipasa" },
        { id: 99, province_id: 7, name: "Gündoğmuş", slug: "gundogmus" },
        { id: 100, province_id: 7, name: "İbradı", slug: "ibradi" },
        { id: 101, province_id: 7, name: "Kaş", slug: "kas" },
        { id: 102, province_id: 7, name: "Kemer", slug: "kemer" },
        { id: 103, province_id: 7, name: "Kepez", slug: "kepez" },
        { id: 104, province_id: 7, name: "Konyaaltı", slug: "konyaalti" },
        { id: 105, province_id: 7, name: "Korkuteli", slug: "korkuteli" },
        { id: 106, province_id: 7, name: "Kumluca", slug: "kumluca" },
        { id: 107, province_id: 7, name: "Manavgat", slug: "manavgat" },
        { id: 108, province_id: 7, name: "Muratpaşa", slug: "muratpasa" },
        { id: 109, province_id: 7, name: "Serik", slug: "serik" },

        // Ardahan (75)
        { id: 110, province_id: 75, name: "Çıldır", slug: "cildir" },
        { id: 111, province_id: 75, name: "Damal", slug: "damal" },
        { id: 112, province_id: 75, name: "Göle", slug: "gole" },
        { id: 113, province_id: 75, name: "Hanak", slug: "hanak" },
        { id: 114, province_id: 75, name: "Merkez", slug: "merkez" },
        { id: 115, province_id: 75, name: "Posof", slug: "posof" },

        // Artvin (8)
        { id: 116, province_id: 8, name: "Ardanuç", slug: "ardanuc" },
        { id: 117, province_id: 8, name: "Arhavi", slug: "arhavi" },
        { id: 118, province_id: 8, name: "Borçka", slug: "borcka" },
        { id: 119, province_id: 8, name: "Hopa", slug: "hopa" },
        { id: 120, province_id: 8, name: "Kemalpaşa", slug: "kemalpasa" },
        { id: 121, province_id: 8, name: "Merkez", slug: "merkez" },
        { id: 122, province_id: 8, name: "Murgul", slug: "murgul" },
        { id: 123, province_id: 8, name: "Şavşat", slug: "savsat" },
        { id: 124, province_id: 8, name: "Yusufeli", slug: "yusufeli" },

        // Aydın (9)
        { id: 125, province_id: 9, name: "Bozdoğan", slug: "bozdogan" },
        { id: 126, province_id: 9, name: "Buharkent", slug: "buharkent" },
        { id: 127, province_id: 9, name: "Çine", slug: "cine" },
        { id: 128, province_id: 9, name: "Didim", slug: "didim" },
        { id: 129, province_id: 9, name: "Efeler", slug: "efeler" },
        { id: 130, province_id: 9, name: "Germencik", slug: "germencik" },
        { id: 131, province_id: 9, name: "İncirliova", slug: "incirliova" },
        { id: 132, province_id: 9, name: "Karacasu", slug: "karacasu" },
        { id: 133, province_id: 9, name: "Karpuzlu", slug: "karpuzlu" },
        { id: 134, province_id: 9, name: "Koçarlı", slug: "kocarlı" },
        { id: 135, province_id: 9, name: "Köşk", slug: "kosk" },
        { id: 136, province_id: 9, name: "Kuşadası", slug: "kusadası" },
        { id: 137, province_id: 9, name: "Kuyucak", slug: "kuyucak" },
        { id: 138, province_id: 9, name: "Nazilli", slug: "nazilli" },
        { id: 139, province_id: 9, name: "Söke", slug: "söke" },
        { id: 140, province_id: 9, name: "Sultanhisar", slug: "sultanhisar" },
        { id: 141, province_id: 9, name: "Yenipazar", slug: "yenipazar" },

        // Balıkesir (10)
        { id: 142, province_id: 10, name: "Altıeylül", slug: "altieylul" },
        { id: 143, province_id: 10, name: "Ayvalık", slug: "ayvalik" },
        { id: 144, province_id: 10, name: "Balya", slug: "balya" },
        { id: 145, province_id: 10, name: "Bandırma", slug: "bandirma" },
        { id: 146, province_id: 10, name: "Bigadiç", slug: "bigadic" },
        { id: 147, province_id: 10, name: "Burhaniye", slug: "burhaniye" },
        { id: 148, province_id: 10, name: "Dursunbey", slug: "dursunbey" },
        { id: 149, province_id: 10, name: "Edremit", slug: "edremit" },
        { id: 150, province_id: 10, name: "Erdek", slug: "erdek" },
        { id: 151, province_id: 10, name: "Gömeç", slug: "gomec" },
        { id: 152, province_id: 10, name: "Gönen", slug: "gonen" },
        { id: 153, province_id: 10, name: "Havran", slug: "havran" },
        { id: 154, province_id: 10, name: "İvrindi", slug: "ivrindi" },
        { id: 155, province_id: 10, name: "Karesi", slug: "karesi" },
        { id: 156, province_id: 10, name: "Kepsut", slug: "kepsut" },
        { id: 157, province_id: 10, name: "Manyas", slug: "manyas" },
        { id: 158, province_id: 10, name: "Marmara", slug: "marmara" },
        { id: 159, province_id: 10, name: "Savaştepe", slug: "savastepe" },
        { id: 160, province_id: 10, name: "Sındırgı", slug: "sindirgi" },
        { id: 161, province_id: 10, name: "Susurluk", slug: "susurluk" },

        // Bartın (74)
        { id: 162, province_id: 74, name: "Amasra", slug: "amasra" },
        { id: 163, province_id: 74, name: "Kurucaşile", slug: "kurucasile" },
        { id: 164, province_id: 74, name: "Merkez", slug: "merkez" },
        { id: 165, province_id: 74, name: "Ulus", slug: "ulus" },

        // Batman (72)
        { id: 166, province_id: 72, name: "Beşiri", slug: "besiri" },
        { id: 167, province_id: 72, name: "Gercüş", slug: "gercus" },
        { id: 168, province_id: 72, name: "Hasankeyf", slug: "hasankeyf" },
        { id: 169, province_id: 72, name: "Kozluk", slug: "kozluk" },
        { id: 170, province_id: 72, name: "Merkez", slug: "merkez" },
        { id: 171, province_id: 72, name: "Sason", slug: "sason" },

        // Bayburt (69)
        { id: 172, province_id: 69, name: "Aydıntepe", slug: "aydintepe" },
        { id: 173, province_id: 69, name: "Demirözü", slug: "demirozu" },
        { id: 174, province_id: 69, name: "Merkez", slug: "merkez" },

        // Bilecik (11)
        { id: 175, province_id: 11, name: "Bozüyük", slug: "bozuyuk" },
        { id: 176, province_id: 11, name: "Gölpazarı", slug: "golpazari" },
        { id: 177, province_id: 11, name: "İnhisar", slug: "inhisar" },
        { id: 178, province_id: 11, name: "Merkez", slug: "merkez" },
        { id: 179, province_id: 11, name: "Osmaneli", slug: "osmaneli" },
        { id: 180, province_id: 11, name: "Pazaryeri", slug: "pazaryeri" },
        { id: 181, province_id: 11, name: "Söğüt", slug: "sogut" },
        { id: 182, province_id: 11, name: "Yenipazar", slug: "yenipazar" },

        // Bingöl (12)
        { id: 183, province_id: 12, name: "Adaklı", slug: "adakli" },
        { id: 184, province_id: 12, name: "Genç", slug: "genc" },
        { id: 185, province_id: 12, name: "Karlıova", slug: "karliova" },
        { id: 186, province_id: 12, name: "Kiğı", slug: "kigi" },
        { id: 187, province_id: 12, name: "Merkez", slug: "merkez" },
        { id: 188, province_id: 12, name: "Solhan", slug: "solhan" },
        { id: 189, province_id: 12, name: "Yayladere", slug: "yayladere" },
        { id: 190, province_id: 12, name: "Yedisu", slug: "yedisu" },

        // Bitlis (13)
        { id: 191, province_id: 13, name: "Adilcevaz", slug: "adilcevaz" },
        { id: 192, province_id: 13, name: "Ahlat", slug: "ahlat" },
        { id: 193, province_id: 13, name: "Güroymak", slug: "guroymak" },
        { id: 194, province_id: 13, name: "Hizan", slug: "hizan" },
        { id: 195, province_id: 13, name: "Merkez", slug: "merkez" },
        { id: 196, province_id: 13, name: "Mutki", slug: "mutki" },
        { id: 197, province_id: 13, name: "Tatvan", slug: "tatvan" },

        // Bolu (14)
        { id: 198, province_id: 14, name: "Dörtdivan", slug: "dortdivan" },
        { id: 199, province_id: 14, name: "Gerede", slug: "gerede" },
        { id: 200, province_id: 14, name: "Göynük", slug: "goynuk" },
        { id: 201, province_id: 14, name: "Kıbrıscık", slug: "kibriscik" },
        { id: 202, province_id: 14, name: "Merkez", slug: "merkez" },
        { id: 203, province_id: 14, name: "Mudurnu", slug: "mudurnu" },
        { id: 204, province_id: 14, name: "Seben", slug: "seben" },
        { id: 205, province_id: 14, name: "Yeniçağa", slug: "yenicaga" },

        // Burdur (15)
        { id: 207, province_id: 15, name: "Ağlasun", slug: "aglasun" },
        { id: 208, province_id: 15, name: "Altınyayla", slug: "altinyayla" },
        { id: 209, province_id: 15, name: "Bucak", slug: "bucak" },
        { id: 210, province_id: 15, name: "Çavdır", slug: "cavdir" },
        { id: 211, province_id: 15, name: "Çeltikçi", slug: "celtikci" },
        { id: 212, province_id: 15, name: "Gölhisar", slug: "golhisar" },
        { id: 213, province_id: 15, name: "Karamanlı", slug: "karamanli" },
        { id: 214, province_id: 15, name: "Kemer", slug: "kemer" },
        { id: 215, province_id: 15, name: "Merkez", slug: "merkez" },
        { id: 216, province_id: 15, name: "Tefenni", slug: "tefenni" },
        { id: 217, province_id: 15, name: "Yeşilova", slug: "yesilova" },

        // Bursa (16)
        { id: 218, province_id: 16, name: "Büyükorhan", slug: "buyukorhan" },
        { id: 219, province_id: 16, name: "Gemlik", slug: "gemlik" },
        { id: 220, province_id: 16, name: "Gürsu", slug: "gursu" },
        { id: 221, province_id: 16, name: "Harmancık", slug: "harmancik" },
        { id: 222, province_id: 16, name: "İnegöl", slug: "inegol" },
        { id: 223, province_id: 16, name: "İznik", slug: "iznik" },
        { id: 224, province_id: 16, name: "Karacabey", slug: "karacabey" },
        { id: 225, province_id: 16, name: "Keles", slug: "keles" },
        { id: 226, province_id: 16, name: "Kestel", slug: "kestel" },
        { id: 227, province_id: 16, name: "Mudanya", slug: "mudanya" },
        { id: 228, province_id: 16, name: "Mustafakemalpaşa", slug: "mustafakemalpasa" },
        { id: 229, province_id: 16, name: "Nilüfer", slug: "nilufer" },
        { id: 230, province_id: 16, name: "Orhaneli", slug: "orhaneli" },
        { id: 231, province_id: 16, name: "Orhangazi", slug: "orhangazi" },
        { id: 232, province_id: 16, name: "Osmangazi", slug: "osmanagi" },
        { id: 233, province_id: 16, name: "Yenişehir", slug: "yenisehir" },
        { id: 234, province_id: 16, name: "Yıldırım", slug: "yildirim" },

        // Çanakkale (17)
        { id: 235, province_id: 17, name: "Ayvacık", slug: "ayvacik" },
        { id: 236, province_id: 17, name: "Bayramiç", slug: "bayramic" },
        { id: 237, province_id: 17, name: "Biga", slug: "biga" },
        { id: 238, province_id: 17, name: "Bozcaada", slug: "bozcaada" },
        { id: 239, province_id: 17, name: "Çan", slug: "can" },
        { id: 240, province_id: 17, name: "Eceabat", slug: "eceabat" },
        { id: 241, province_id: 17, name: "Ezine", slug: "ezine" },
        { id: 242, province_id: 17, name: "Gelibolu", slug: "gelibolu" },
        { id: 243, province_id: 17, name: "Gökçeada", slug: "gokceada" },
        { id: 244, province_id: 17, name: "Lapseki", slug: "lapsaki" },
        { id: 245, province_id: 17, name: "Merkez", slug: "merkez" },
        { id: 246, province_id: 17, name: "Yenice", slug: "yenice" },

        // Çankırı (18)
        { id: 247, province_id: 18, name: "Atkaracalar", slug: "atkaracalar" },
        { id: 248, province_id: 18, name: "Bayramören", slug: "bayramoren" },
        { id: 249, province_id: 18, name: "Çerkeş", slug: "cerkes" },
        { id: 250, province_id: 18, name: "Eldivan", slug: "eldivan" },
        { id: 251, province_id: 18, name: "Ilgaz", slug: "ilgaz" },
        { id: 252, province_id: 18, name: "Kızılırmak", slug: "kizilirmak" },
        { id: 253, province_id: 18, name: "Korgun", slug: "korgun" },
        { id: 254, province_id: 18, name: "Kurşunlu", slug: "kursumlu" },
        { id: 255, province_id: 18, name: "Merkez", slug: "merkez" },
        { id: 256, province_id: 18, name: "Orta", slug: "orta" },
        { id: 257, province_id: 18, name: "Şabanözü", slug: "sabanozu" },
        { id: 258, province_id: 18, name: "Yapraklı", slug: "yaprakli" },

        // Çorum (19)
        { id: 259, province_id: 19, name: "Alaca", slug: "alaca" },
        { id: 260, province_id: 19, name: "Bayat", slug: "bayat" },
        { id: 261, province_id: 19, name: "Boğazkale", slug: "bogazkale" },
        { id: 262, province_id: 19, name: "Dodurga", slug: "dodurga" },
        { id: 263, province_id: 19, name: "İskilip", slug: "iskilip" },
        { id: 264, province_id: 19, name: "Kargı", slug: "kargi" },
        { id: 265, province_id: 19, name: "Laçin", slug: "lacin" },
        { id: 266, province_id: 19, name: "Mecitözü", slug: "mecitozu" },
        { id: 267, province_id: 19, name: "Merkez", slug: "merkez" },
        { id: 268, province_id: 19, name: "Oğuzlar", slug: "oguzlar" },
        { id: 269, province_id: 19, name: "Ortaköy", slug: "ortakoy" },
        { id: 270, province_id: 19, name: "Osmancık", slug: "osmancik" },
        { id: 271, province_id: 19, name: "Sungurlu", slug: "sungurlu" },
        { id: 272, province_id: 19, name: "Uğurludağ", slug: "ugurludag" },

        // Denizli (20)
        { id: 273, province_id: 20, name: "Acıpayam", slug: "acipayam" },
        { id: 274, province_id: 20, name: "Babadağ", slug: "babadag" },
        { id: 275, province_id: 20, name: "Baklan", slug: "baklan" },
        { id: 276, province_id: 20, name: "Bekilli", slug: "bekilli" },
        { id: 277, province_id: 20, name: "Beyağaç", slug: "beyagac" },
        { id: 278, province_id: 20, name: "Bozkurt", slug: "bozkurt" },
        { id: 279, province_id: 20, name: "Buldan", slug: "buldan" },
        { id: 280, province_id: 20, name: "Çal", slug: "cal" },
        { id: 281, province_id: 20, name: "Çameli", slug: "cameli" },
        { id: 282, province_id: 20, name: "Çardak", slug: "cardak" },
        { id: 283, province_id: 20, name: "Çivril", slug: "civril" },
        { id: 284, province_id: 20, name: "Güney", slug: "guney" },
        { id: 285, province_id: 20, name: "Honaz", slug: "honaz" },
        { id: 286, province_id: 20, name: "Kale", slug: "kale" },
        { id: 287, province_id: 20, name: "Merkezefendi", slug: "merkezefendi" },
        { id: 288, province_id: 20, name: "Pamukkale", slug: "pamukkale" },
        { id: 289, province_id: 20, name: "Sarayköy", slug: "saraykoy" },
        { id: 290, province_id: 20, name: "Serinhisar", slug: "serinhisar" },
        { id: 291, province_id: 20, name: "Tavas", slug: "tavas" },

        // Diyarbakır (21)
        { id: 292, province_id: 21, name: "Bağlar", slug: "baglar" },
        { id: 293, province_id: 21, name: "Bismil", slug: "bismil" },
        { id: 294, province_id: 21, name: "Çermik", slug: "cermik" },
        { id: 295, province_id: 21, name: "Çınar", slug: "cinar" },
        { id: 296, province_id: 21, name: "Çüngüş", slug: "cungus" },
        { id: 297, province_id: 21, name: "Dicle", slug: "dicle" },
        { id: 298, province_id: 21, name: "Eğil", slug: "egil" },
        { id: 299, province_id: 21, name: "Ergani", slug: "ergani" },
        { id: 300, province_id: 21, name: "Hani", slug: "hani" },
        { id: 301, province_id: 21, name: "Hazro", slug: "hazro" },
        { id: 302, province_id: 21, name: "Kayapınar", slug: "kayapinar" },
        { id: 303, province_id: 21, name: "Kocaköy", slug: "kocakoy" },
        { id: 304, province_id: 21, name: "Kulp", slug: "kulp" },
        { id: 305, province_id: 21, name: "Lice", slug: "lice" },
        { id: 306, province_id: 21, name: "Silvan", slug: "silvan" },
        { id: 307, province_id: 21, name: "Sur", slug: "sur" },
        { id: 308, province_id: 21, name: "Yenişehir", slug: "yenisehir" },

        // Düzce (81)
        { id: 309, province_id: 81, name: "Akçakoca", slug: "akcakoca" },
        { id: 310, province_id: 81, name: "Çilimli", slug: "cilimli" },
        { id: 311, province_id: 81, name: "Cumayeri", slug: "cumayeri" },
        { id: 312, province_id: 81, name: "Gölyaka", slug: "golyaka" },
        { id: 313, province_id: 81, name: "Gümüşova", slug: "gumusova" },
        { id: 314, province_id: 81, name: "Kaynaşlı", slug: "kaynasil" },
        { id: 315, province_id: 81, name: "Merkez", slug: "merkez" },
        { id: 316, province_id: 81, name: "Yığılca", slug: "yigilca" },

        // Edirne (22)
        { id: 317, province_id: 22, name: "Enez", slug: "enez" },
        { id: 318, province_id: 22, name: "Havsa", slug: "havsa" },
        { id: 319, province_id: 22, name: "İpsala", slug: "ipsala" },
        { id: 320, province_id: 22, name: "Keşan", slug: "kesan" },
        { id: 321, province_id: 22, name: "Lalapaşa", slug: "lalapasa" },
        { id: 322, province_id: 22, name: "Meriç", slug: "meric" },
        { id: 323, province_id: 22, name: "Merkez", slug: "merkez" },
        { id: 324, province_id: 22, name: "Süloğlu", slug: "suloglu" },
        { id: 325, province_id: 22, name: "Uzunköprü", slug: "uzunkopru" },

        // Elazığ (23)
        { id: 326, province_id: 23, name: "Ağın", slug: "agin" },
        { id: 327, province_id: 23, name: "Alacakaya", slug: "alacakaya" },
        { id: 328, province_id: 23, name: "Arıcak", slug: "aricak" },
        { id: 329, province_id: 23, name: "Baskil", slug: "baskil" },
        { id: 330, province_id: 23, name: "Karakoçan", slug: "karakocan" },
        { id: 331, province_id: 23, name: "Keban", slug: "keban" },
        { id: 332, province_id: 23, name: "Kovancılar", slug: "kovancilar" },
        { id: 333, province_id: 23, name: "Maden", slug: "maden" },
        { id: 334, province_id: 23, name: "Merkez", slug: "merkez" },
        { id: 335, province_id: 23, name: "Palu", slug: "palu" },
        { id: 336, province_id: 23, name: "Sivrice", slug: "sivrice" },

        // Erzincan (24)
        { id: 337, province_id: 24, name: "Çayırlı", slug: "cayirli" },
        { id: 338, province_id: 24, name: "İliç", slug: "ilic" },
        { id: 339, province_id: 24, name: "Kemah", slug: "kemah" },
        { id: 340, province_id: 24, name: "Kemaliye", slug: "kemaliye" },
        { id: 341, province_id: 24, name: "Merkez", slug: "merkez" },
        { id: 342, province_id: 24, name: "Otlukbeli", slug: "otlukbeli" },
        { id: 343, province_id: 24, name: "Refahiye", slug: "refahiye" },
        { id: 344, province_id: 24, name: "Tercan", slug: "tercan" },
        { id: 345, province_id: 24, name: "Üzümlü", slug: "uzumlu" },

        // Erzurum (25)
        { id: 346, province_id: 25, name: "Aşkale", slug: "askale" },
        { id: 347, province_id: 25, name: "Aziziye", slug: "aziziye" },
        { id: 348, province_id: 25, name: "Çat", slug: "cat" },
        { id: 349, province_id: 25, name: "Hınıs", slug: "hinis" },
        { id: 350, province_id: 25, name: "Horasan", slug: "horasan" },
        { id: 351, province_id: 25, name: "İspir", slug: "ispir" },
        { id: 352, province_id: 25, name: "Karaçoban", slug: "karacoban" },
        { id: 353, province_id: 25, name: "Karayazı", slug: "karayazi" },
        { id: 354, province_id: 25, name: "Köprüköy", slug: "koprukoy" },
        { id: 355, province_id: 25, name: "Narman", slug: "narman" },
        { id: 356, province_id: 25, name: "Oltu", slug: "olt" },
        { id: 357, province_id: 25, name: "Olur", slug: "olur" },
        { id: 358, province_id: 25, name: "Palandöken", slug: "palandoken" },
        { id: 359, province_id: 25, name: "Pasinler", slug: "pasinler" },
        { id: 360, province_id: 25, name: "Pazaryolu", slug: "pazaryolu" },
        { id: 361, province_id: 25, name: "Şenkaya", slug: "senkaya" },
        { id: 362, province_id: 25, name: "Tekman", slug: "tekman" },
        { id: 363, province_id: 25, name: "Tortum", slug: "tortum" },
        { id: 364, province_id: 25, name: "Uzundere", slug: "uzundere" },
        { id: 365, province_id: 25, name: "Yakutiye", slug: "yakutiye" },

        // Eskişehir (26)
        { id: 366, province_id: 26, name: "Alpu", slug: "alp" },
        { id: 367, province_id: 26, name: "Beylikova", slug: "beylikova" },
        { id: 368, province_id: 26, name: "Çifteler", slug: "cifteler" },
        { id: 369, province_id: 26, name: "Günyüzü", slug: "gunyuzu" },
        { id: 370, province_id: 26, name: "Han", slug: "han" },
        { id: 371, province_id: 26, name: "İnönü", slug: "inonu" },
        { id: 372, province_id: 26, name: "Mahmudiye", slug: "mahmudiye" },
        { id: 373, province_id: 26, name: "Mihalgazi", slug: "mihalgazi" },
        { id: 374, province_id: 26, name: "Mihalıççık", slug: "mihaliccik" },
        { id: 375, province_id: 26, name: "Odunpazarı", slug: "odunpazar" },
        { id: 376, province_id: 26, name: "Sarıcakaya", slug: "saricakaya" },
        { id: 377, province_id: 26, name: "Seyitgazi", slug: "seyitgazi" },
        { id: 378, province_id: 26, name: "Sivrihisar", slug: "sivrihisar" },
        { id: 379, province_id: 26, name: "Tepebaşı", slug: "tepebas" },

        // Gaziantep (27)
        { id: 380, province_id: 27, name: "Araban", slug: "araban" },
        { id: 381, province_id: 27, name: "İslahiye", slug: "islahiye" },
        { id: 382, province_id: 27, name: "Karkamış", slug: "karkamis" },
        { id: 383, province_id: 27, name: "Nizip", slug: "nizip" },
        { id: 384, province_id: 27, name: "Nurdağı", slug: "nurdagi" },
        { id: 385, province_id: 27, name: "Oğuzeli", slug: "oguzeli" },
        { id: 386, province_id: 27, name: "Şahinbey", slug: "sahinbey" },
        { id: 387, province_id: 27, name: "Şehitkamil", slug: "sehitkamil" },
        { id: 388, province_id: 27, name: "Yavuzeli", slug: "yavuzeli" },

        // Giresun (28)
        { id: 389, province_id: 28, name: "Alucra", slug: "alucra" },
        { id: 390, province_id: 28, name: "Bulancak", slug: "bulancak" },
        { id: 391, province_id: 28, name: "Çamoluk", slug: "camoluk" },
        { id: 392, province_id: 28, name: "Çanakçı", slug: "canakci" },
        { id: 393, province_id: 28, name: "Dereli", slug: "dereli" },
        { id: 394, province_id: 28, name: "Doğankent", slug: "dogankent" },
        { id: 395, province_id: 28, name: "Espiye", slug: "espiye" },
        { id: 396, province_id: 28, name: "Eynesil", slug: "eynesil" },
        { id: 397, province_id: 28, name: "Görele", slug: "gorele" },
        { id: 398, province_id: 28, name: "Güce", slug: "guc" },
        { id: 399, province_id: 28, name: "Keşap", slug: "kesap" },
        { id: 400, province_id: 28, name: "Merkez", slug: "merkez" },
        { id: 401, province_id: 28, name: "Piraziz", slug: "piraziz" },
        { id: 402, province_id: 28, name: "Şebinkarahisar", slug: "sebinkarahisar" },
        { id: 403, province_id: 28, name: "Tirebolu", slug: "tirebolu" },
        { id: 404, province_id: 28, name: "Yağlıdere", slug: "yagliyere" },

        // Gümüşhane (29)
        { id: 405, province_id: 29, name: "Kelkit", slug: "kelkit" },
        { id: 406, province_id: 29, name: "Köse", slug: "kose" },
        { id: 407, province_id: 29, name: "Kürtün", slug: "kurtun" },
        { id: 408, province_id: 29, name: "Merkez", slug: "merkez" },
        { id: 409, province_id: 29, name: "Şiran", slug: "siran" },
        { id: 410, province_id: 29, name: "Torul", slug: "torul" },

        // Hakkari (30)
        { id: 411, province_id: 30, name: "Çukurca", slug: "cukurca" },
        { id: 412, province_id: 30, name: "Derecik", slug: "derecik" },
        { id: 413, province_id: 30, name: "Merkez", slug: "merkez" },
        { id: 414, province_id: 30, name: "Şemdinli", slug: "semdinli" },
        { id: 415, province_id: 30, name: "Yüksekova", slug: "yuksekova" },

        // Hatay (31)
        { id: 416, province_id: 31, name: "Altınözü", slug: "altinozu" },
        { id: 417, province_id: 31, name: "Antakya", slug: "antakya" },
        { id: 418, province_id: 31, name: "Arsuz", slug: "arsuz" },
        { id: 419, province_id: 31, name: "Belen", slug: "belen" },
        { id: 420, province_id: 31, name: "Defne", slug: "defne" },
        { id: 421, province_id: 31, name: "Dörtyol", slug: "dortyol" },
        { id: 422, province_id: 31, name: "Erzin", slug: "erzin" },
        { id: 423, province_id: 31, name: "Hassa", slug: "hassa" },
        { id: 424, province_id: 31, name: "İskenderun", slug: "iskenderun" },
        { id: 425, province_id: 31, name: "Kırıkhan", slug: "kirikhan" },
        { id: 426, province_id: 31, name: "Kumlu", slug: "kumlu" },
        { id: 427, province_id: 31, name: "Payas", slug: "payas" },
        { id: 428, province_id: 31, name: "Reyhanlı", slug: "reyhanli" },
        { id: 429, province_id: 31, name: "Samandağ", slug: "samandag" },
        { id: 430, province_id: 31, name: "Yayladağı", slug: "yayladagi" },

        // Iğdır (76)
        { id: 431, province_id: 76, name: "Aralık", slug: "aralik" },
        { id: 432, province_id: 76, name: "Karakoyunlu", slug: "karakoyunlu" },
        { id: 433, province_id: 76, name: "Merkez", slug: "merkez" },
        { id: 434, province_id: 76, name: "Tuzluca", slug: "tuzluca" },

        // Isparta (32)
        { id: 435, province_id: 32, name: "Aksu", slug: "aksu" },
        { id: 436, province_id: 32, name: "Atabey", slug: "atabey" },
        { id: 437, province_id: 32, name: "Eğirdir", slug: "egirdir" },
        { id: 438, province_id: 32, name: "Gelendost", slug: "gelendost" },
        { id: 439, province_id: 32, name: "Gönen", slug: "gonen" },
        { id: 440, province_id: 32, name: "Keçiborlu", slug: "keciborlu" },
        { id: 441, province_id: 32, name: "Merkez", slug: "merkez" },
        { id: 442, province_id: 32, name: "Senirkent", slug: "senirkent" },
        { id: 443, province_id: 32, name: "Sütçüler", slug: "sutculer" },
        { id: 444, province_id: 32, name: "Şarkikaraağaç", slug: "sarkikaraagac" },
        { id: 445, province_id: 32, name: "Uluborlu", slug: "uluborlu" },
        { id: 446, province_id: 32, name: "Yalvaç", slug: "yalvac" },
        { id: 447, province_id: 32, name: "Yenişarbademli", slug: "yenisarbademli" },

        // İstanbul (34)
        { id: 448, province_id: 34, name: "Adalar", slug: "adalar" },
        { id: 449, province_id: 34, name: "Arnavutköy", slug: "arnavutkoy" },
        { id: 450, province_id: 34, name: "Ataşehir", slug: "atesehir" },
        { id: 451, province_id: 34, name: "Avcılar", slug: "avcilar" },
        { id: 452, province_id: 34, name: "Bağcılar", slug: "bagcilar" },
        { id: 453, province_id: 34, name: "Bahçelievler", slug: "bahcelievler" },
        { id: 454, province_id: 34, name: "Bakırköy", slug: "bakirkoy" },
        { id: 455, province_id: 34, name: "Başakşehir", slug: "basaksehir" },
        { id: 456, province_id: 34, name: "Bayrampaşa", slug: "bayrampasa" },
        { id: 457, province_id: 34, name: "Beşiktaş", slug: "besiktas" },
        { id: 458, province_id: 34, name: "Beykoz", slug: "beykoz" },
        { id: 459, province_id: 34, name: "Beylikdüzü", slug: "beylikduzu" },
        { id: 460, province_id: 34, name: "Beyoğlu", slug: "beyoglu" },
        { id: 461, province_id: 34, name: "Büyükçekmece", slug: "buyukcekmece" },
        { id: 462, province_id: 34, name: "Çatalca", slug: "catalca" },
        { id: 463, province_id: 34, name: "Çekmeköy", slug: "cekmekoy" },
        { id: 464, province_id: 34, name: "Esenler", slug: "esenler" },
        { id: 465, province_id: 34, name: "Esenyurt", slug: "esenyurt" },
        { id: 466, province_id: 34, name: "Eyüpsultan", slug: "eyup sultan" },
        { id: 467, province_id: 34, name: "Fatih", slug: "fatih" },
        { id: 468, province_id: 34, name: "Gaziosmanpaşa", slug: "gaziosmanpasa" },
        { id: 469, province_id: 34, name: "Güngören", slug: "gungoren" },
        { id: 470, province_id: 34, name: "Kadıköy", slug: "kadikoy" },
        { id: 471, province_id: 34, name: "Kağıthane", slug: "kagithane" },
        { id: 472, province_id: 34, name: "Kartal", slug: "kartal" },
        { id: 473, province_id: 34, name: "Küçükçekmece", slug: "kucukcekmece" },
        { id: 474, province_id: 34, name: "Maltepe", slug: "maltepe" },
        { id: 475, province_id: 34, name: "Pendik", slug: "pendik" },
        { id: 476, province_id: 34, name: "Sancaktepe", slug: "sancaktepe" },
        { id: 477, province_id: 34, name: "Sarıyer", slug: "sariyer" },
        { id: 478, province_id: 34, name: "Silivri", slug: "silivri" },
        { id: 479, province_id: 34, name: "Sultanbeyli", slug: "sultanbeyli" },
        { id: 480, province_id: 34, name: "Sultangazi", slug: "sultangazi" },
        { id: 481, province_id: 34, name: "Şile", slug: "sile" },
        { id: 482, province_id: 34, name: "Şişli", slug: "sisli" },
        { id: 483, province_id: 34, name: "Tuzla", slug: "tuzla" },
        { id: 484, province_id: 34, name: "Ümraniye", slug: "umraniye" },
        { id: 485, province_id: 34, name: "Üsküdar", slug: "uskudar" },
        { id: 486, province_id: 34, name: "Zeytinburnu", slug: "zeytinburnu" },

        // İzmir (35)
        { id: 487, province_id: 35, name: "Aliağa", slug: "aliaga" },
        { id: 488, province_id: 35, name: "Balçova", slug: "balcova" },
        { id: 489, province_id: 35, name: "Bayındır", slug: "bayindir" },
        { id: 490, province_id: 35, name: "Bayraklı", slug: "bayrakli" },
        { id: 491, province_id: 35, name: "Bergama", slug: "bergama" },
        { id: 492, province_id: 35, name: "Beydağ", slug: "beydag" },
        { id: 493, province_id: 35, name: "Bornova", slug: "bornova" },
        { id: 494, province_id: 35, name: "Buca", slug: "buca" },
        { id: 495, province_id: 35, name: "Çeşme", slug: "cesme" },
        { id: 496, province_id: 35, name: "Çiğli", slug: "cigli" },
        { id: 497, province_id: 35, name: "Dikili", slug: "dikili" },
        { id: 498, province_id: 35, name: "Foça", slug: "foca" },
        { id: 499, province_id: 35, name: "Gaziemir", slug: "gaziemir" },
        { id: 500, province_id: 35, name: "Güzelbahçe", slug: "guzelbahce" },
        { id: 501, province_id: 35, name: "Karabağlar", slug: "karabaglar" },
        { id: 502, province_id: 35, name: "Karaburun", slug: "karaburun" },
        { id: 503, province_id: 35, name: "Karşıyaka", slug: "karşiyaka" },
        { id: 504, province_id: 35, name: "Kemalpaşa", slug: "kemalpasa" },
        { id: 505, province_id: 35, name: "Kınık", slug: "kinik" },
        { id: 506, province_id: 35, name: "Kiraz", slug: "kiraz" },
        { id: 507, province_id: 35, name: "Konak", slug: "konak" },
        { id: 508, province_id: 35, name: "Menderes", slug: "menderes" },
        { id: 509, province_id: 35, name: "Menemen", slug: "menemen" },
        { id: 510, province_id: 35, name: "Narlıdere", slug: "narlidere" },
        { id: 511, province_id: 35, name: "Ödemiş", slug: "odemis" },
        { id: 512, province_id: 35, name: "Seferihisar", slug: "seferihizar" },
        { id: 513, province_id: 35, name: "Selçuk", slug: "selcuk" },
        { id: 514, province_id: 35, name: "Tire", slug: "tire" },
        { id: 515, province_id: 35, name: "Torbalı", slug: "torbali" },
        { id: 516, province_id: 35, name: "Urla", slug: "urla" },

        // Kahramanmaraş (46)
        { id: 517, province_id: 46, name: "Afşin", slug: "afsin" },
        { id: 518, province_id: 46, name: "Andırın", slug: "andirin" },
        { id: 519, province_id: 46, name: "Çağlayancerit", slug: "caglayancerit" },
        { id: 520, province_id: 46, name: "Dulkadiroğlu", slug: "dulkadiroglu" },
        { id: 521, province_id: 46, name: "Ekinözü", slug: "ekinozu" },
        { id: 522, province_id: 46, name: "Elbistan", slug: "elbistan" },
        { id: 523, province_id: 46, name: "Göksun", slug: "goksun" },
        { id: 524, province_id: 46, name: "Nurhak", slug: "nurhak" },
        { id: 525, province_id: 46, name: "Onikişubat", slug: "onikisubat" },
        { id: 526, province_id: 46, name: "Pazarcık", slug: "pazarcik" },
        { id: 527, province_id: 46, name: "Türkoğlu", slug: "turkoglu" },

        // Karabük (78)
        { id: 528, province_id: 78, name: "Eflani", slug: "eflani" },
        { id: 529, province_id: 78, name: "Eskipazar", slug: "eskipazar" },
        { id: 530, province_id: 78, name: "Merkez", slug: "merkez" },
        { id: 531, province_id: 78, name: "Ovacık", slug: "ovacik" },
        { id: 532, province_id: 78, name: "Safranbolu", slug: "safranbolu" },
        { id: 533, province_id: 78, name: "Yenice", slug: "yenice" },

        // Karaman (70)
        { id: 534, province_id: 70, name: "Ayrancı", slug: "ayranci" },
        { id: 535, province_id: 70, name: "Başyayla", slug: "basyayla" },
        { id: 536, province_id: 70, name: "Ermenek", slug: "ermenek" },
        { id: 537, province_id: 70, name: "Kazımkarabekir", slug: "kazimkarabekir" },
        { id: 538, province_id: 70, name: "Merkez", slug: "merkez" },
        { id: 539, province_id: 70, name: "Sarıveliler", slug: "sariveliler" },

        // Kars (36)
        { id: 540, province_id: 36, name: "Akyaka", slug: "akyaka" },
        { id: 541, province_id: 36, name: "Arpaçay", slug: "arpacay" },
        { id: 542, province_id: 36, name: "Digor", slug: "digor" },
        { id: 543, province_id: 36, name: "Kağızman", slug: "kagizman" },
        { id: 544, province_id: 36, name: "Merkez", slug: "merkez" },
        { id: 545, province_id: 36, name: "Sarıkamış", slug: "sarikamis" },
        { id: 546, province_id: 36, name: "Selim", slug: "selim" },
        { id: 547, province_id: 36, name: "Susuz", slug: "susuz" },

        // Kastamonu (37)
        { id: 548, province_id: 37, name: "Abana", slug: "abana" },
        { id: 549, province_id: 37, name: "Ağlı", slug: "agli" },
        { id: 550, province_id: 37, name: "Araç", slug: "arac" },
        { id: 551, province_id: 37, name: "Azdavay", slug: "azdavay" },
        { id: 552, province_id: 37, name: "Bozkurt", slug: "bozkurt" },
        { id: 553, province_id: 37, name: "Cide", slug: "cide" },
        { id: 554, province_id: 37, name: "Çatalzeytin", slug: "catalzeytin" },
        { id: 555, province_id: 37, name: "Daday", slug: "daday" },
        { id: 556, province_id: 37, name: "Devrekani", slug: "devrekani" },
        { id: 557, province_id: 37, name: "Doğanyurt", slug: "doganyurt" },
        { id: 558, province_id: 37, name: "Hanönü", slug: "hanonu" },
        { id: 559, province_id: 37, name: "İhsangazi", slug: "ihsangazi" },
        { id: 560, province_id: 37, name: "İnebolu", slug: "inebolu" },
        { id: 561, province_id: 37, name: "Küre", slug: "kure" },
        { id: 562, province_id: 37, name: "Merkez", slug: "merkez" },
        { id: 563, province_id: 37, name: "Pınarbaşı", slug: "pinarbasi" },
        { id: 564, province_id: 37, name: "Seydiler", slug: "seydiler" },
        { id: 565, province_id: 37, name: "Şenpazar", slug: "senpazar" },
        { id: 566, province_id: 37, name: "Taşköprü", slug: "taskopru" },
        { id: 567, province_id: 37, name: "Tosya", slug: "tosya" },

        // Kayseri (38)
        { id: 568, province_id: 38, name: "Akkışla", slug: "akkisla" },
        { id: 569, province_id: 38, name: "Bünyan", slug: "bunyan" },
        { id: 570, province_id: 38, name: "Develi", slug: "develi" },
        { id: 571, province_id: 38, name: "Felahiye", slug: "felahiye" },
        { id: 572, province_id: 38, name: "Hacılar", slug: "hacilar" },
        { id: 573, province_id: 38, name: "İncesu", slug: "incesu" },
        { id: 574, province_id: 38, name: "Kocasinan", slug: "kocasinan" },
        { id: 575, province_id: 38, name: "Melikgazi", slug: "melikgazi" },
        { id: 576, province_id: 38, name: "Özvatan", slug: "ozvatan" },
        { id: 577, province_id: 38, name: "Pınarbaşı", slug: "pinarbasi" },
        { id: 578, province_id: 38, name: "Sarıoğlan", slug: "sarioğlan" },
        { id: 579, province_id: 38, name: "Sarız", slug: "sariz" },
        { id: 580, province_id: 38, name: "Talas", slug: "talas" },
        { id: 581, province_id: 38, name: "Tomarza", slug: "tomarza" },
        { id: 582, province_id: 38, name: "Yahyalı", slug: "yahyali" },
        { id: 583, province_id: 38, name: "Yeşilhisar", slug: "yesilhisar" },

        // Kırıkkale (71)
        { id: 584, province_id: 71, name: "Bahşılı", slug: "bahsil" },
        { id: 585, province_id: 71, name: "Balışeyh", slug: "baliseyh" },
        { id: 586, province_id: 71, name: "Çelebi", slug: "celbi" },
        { id: 587, province_id: 71, name: "Delice", slug: "delice" },
        { id: 588, province_id: 71, name: "Karakeçili", slug: "karakeceli" },
        { id: 589, province_id: 71, name: "Keskin", slug: "keskin" },
        { id: 590, province_id: 71, name: "Merkez", slug: "merkez" },
        { id: 591, province_id: 71, name: "Sulakyurt", slug: "sulakyurt" },
        { id: 592, province_id: 71, name: "Yahşihan", slug: "yahsihan" },

        // Kırklareli (39)
        { id: 593, province_id: 39, name: "Babaeski", slug: "babaeski" },
        { id: 594, province_id: 39, name: "Demirköy", slug: "demirkoy" },
        { id: 595, province_id: 39, name: "Kofçaz", slug: "kofcaz" },
        { id: 596, province_id: 39, name: "Lüleburgaz", slug: "luleburgaz" },
        { id: 597, province_id: 39, name: "Merkez", slug: "merkez" },
        { id: 598, province_id: 39, name: "Pehlivanköy", slug: "pehlivankoy" },
        { id: 599, province_id: 39, name: "Pınarhisar", slug: "pinarhisar" },
        { id: 600, province_id: 39, name: "Vize", slug: "vize" },

        // Kırşehir (40)
        { id: 601, province_id: 40, name: "Akçakent", slug: "akcakent" },
        { id: 602, province_id: 40, name: "Akpınar", slug: "akpinar" },
        { id: 603, province_id: 40, name: "Boztepe", slug: "boztepe" },
        { id: 604, province_id: 40, name: "Çiçekdağı", slug: "cicekdagi" },
        { id: 605, province_id: 40, name: "Kaman", slug: "kaman" },
        { id: 606, province_id: 40, name: "Merkez", slug: "merkez" },
        { id: 607, province_id: 40, name: "Mucur", slug: "mucur" },

        // Kilis (79)
        { id: 608, province_id: 79, name: "Elbeyli", slug: "elbeyli" },
        { id: 609, province_id: 79, name: "Merkez", slug: "merkez" },
        { id: 610, province_id: 79, name: "Musabeyli", slug: "musabeyli" },
        { id: 611, province_id: 79, name: "Polateli", slug: "polateli" },

        // Kocaeli (41)
        { id: 612, province_id: 41, name: "Başiskele", slug: "basiskele" },
        { id: 613, province_id: 41, name: "Çayırova", slug: "cayirova" },
        { id: 614, province_id: 41, name: "Darıca", slug: "darica" },
        { id: 615, province_id: 41, name: "Derince", slug: "derince" },
        { id: 616, province_id: 41, name: "Dilovası", slug: "dilovasi" },
        { id: 617, province_id: 41, name: "Gebze", slug: "gebze" },
        { id: 618, province_id: 41, name: "Gölcük", slug: "golcu" },
        { id: 619, province_id: 41, name: "İzmit", slug: "izmit" },
        { id: 620, province_id: 41, name: "Kandıra", slug: "kandira" },
        { id: 621, province_id: 41, name: "Karamürsel", slug: "karamursel" },
        { id: 622, province_id: 41, name: "Kartepe", slug: "kartepe" },
        { id: 623, province_id: 41, name: "Körfez", slug: "korfez" },

        // Konya (42)
        { id: 624, province_id: 42, name: "Ahırlı", slug: "ahirli" },
        { id: 625, province_id: 42, name: "Akören", slug: "akoren" },
        { id: 626, province_id: 42, name: "Akşehir", slug: "aksehir" },
        { id: 627, province_id: 42, name: "Altınekin", slug: "altinekin" },
        { id: 628, province_id: 42, name: "Beyşehir", slug: "beysehir" },
        { id: 629, province_id: 42, name: "Bozkır", slug: "bozkir" },
        { id: 630, province_id: 42, name: "Cihanbeyli", slug: "cihanbeyli" },
        { id: 631, province_id: 42, name: "Çeltik", slug: "celtik" },
        { id: 632, province_id: 42, name: "Çumra", slug: "cumra" },
        { id: 633, province_id: 42, name: "Derbent", slug: "derbent" },
        { id: 634, province_id: 42, name: "Derebucak", slug: "derebuçak" },
        { id: 635, province_id: 42, name: "Doğanhisar", slug: "doganhisar" },
        { id: 636, province_id: 42, name: "Emirgazi", slug: "emirgazi" },
        { id: 637, province_id: 42, name: "Ereğli", slug: "eregli" },
        { id: 638, province_id: 42, name: "Güneysınır", slug: "gunesinir" },
        { id: 639, province_id: 42, name: "Hadim", slug: "hadim" },
        { id: 640, province_id: 42, name: "Halkapınar", slug: "halkapinar" },
        { id: 641, province_id: 42, name: "Hüyük", slug: "huyuk" },
        { id: 642, province_id: 42, name: "Ilgın", slug: "ilgin" },
        { id: 643, province_id: 42, name: "Kadınhanı", slug: "kadinhani" },
        { id: 644, province_id: 42, name: "Karapınar", slug: "karapinar" },
        { id: 645, province_id: 42, name: "Karatay", slug: "karatay" },
        { id: 646, province_id: 42, name: "Kulu", slug: "kulu" },
        { id: 647, province_id: 42, name: "Meram", slug: "meram" },
        { id: 648, province_id: 42, name: "Sarayönü", slug: "sarayonu" },
        { id: 649, province_id: 42, name: "Selçuklu", slug: "selcuklu" },
        { id: 650, province_id: 42, name: "Seydişehir", slug: "seydisehir" },
        { id: 651, province_id: 42, name: "Taşkent", slug: "taskent" },
        { id: 652, province_id: 42, name: "Tuzlukçu", slug: "tuzlukcu" },
        { id: 653, province_id: 42, name: "Yalıhüyük", slug: "yalihuyuk" },
        { id: 654, province_id: 42, name: "Yunak", slug: "yunak" },

        // Kütahya (43)
        { id: 655, province_id: 43, name: "Altıntaş", slug: "altintas" },
        { id: 656, province_id: 43, name: "Aslanapa", slug: "aslanapa" },
        { id: 657, province_id: 43, name: "Çavdarhisar", slug: "cavdarhisar" },
        { id: 658, province_id: 43, name: "Domaniç", slug: "domanic" },
        { id: 659, province_id: 43, name: "Dumlupınar", slug: "dumlupinar" },
        { id: 660, province_id: 43, name: "Emet", slug: "emet" },
        { id: 661, province_id: 43, name: "Gediz", slug: "gediz" },
        { id: 662, province_id: 43, name: "Hisarcık", slug: "hisarkik" },
        { id: 663, province_id: 43, name: "Merkez", slug: "merkez" },
        { id: 664, province_id: 43, name: "Pazarlar", slug: "pazarlar" },
        { id: 665, province_id: 43, name: "Şaphane", slug: "saphane" },
        { id: 666, province_id: 43, name: "Simav", slug: "simav" },
        { id: 667, province_id: 43, name: "Tavşanlı", slug: "tavsanli" },

        // Malatya (44)
        { id: 668, province_id: 44, name: "Akçadağ", slug: "akcadag" },
        { id: 669, province_id: 44, name: "Arapgir", slug: "arapgir" },
        { id: 670, province_id: 44, name: "Arguvan", slug: "arguvan" },
        { id: 671, province_id: 44, name: "Battalgazi", slug: "battalgazi" },
        { id: 672, province_id: 44, name: "Darende", slug: "darende" },
        { id: 673, province_id: 44, name: "Doğanşehir", slug: "dogansehir" },
        { id: 674, province_id: 44, name: "Doğanyol", slug: "doganyol" },
        { id: 675, province_id: 44, name: "Hekimhan", slug: "hekimhan" },
        { id: 676, province_id: 44, name: "Kale", slug: "kale" },
        { id: 677, province_id: 44, name: "Kuluncak", slug: "kuluncak" },
        { id: 678, province_id: 44, name: "Pütürge", slug: "puturge" },
        { id: 679, province_id: 44, name: "Yazıhan", slug: "yazihani" },
        { id: 680, province_id: 44, name: "Yeşilyurt", slug: "yesilyurt" },

        // Manisa (45)
        { id: 681, province_id: 45, name: "Ahmetli", slug: "ahmetli" },
        { id: 682, province_id: 45, name: "Akhisar", slug: "akhisar" },
        { id: 683, province_id: 45, name: "Alaşehir", slug: "alasheir" },
        { id: 684, province_id: 45, name: "Demirci", slug: "demirci" },
        { id: 685, province_id: 45, name: "Gölmarmara", slug: "golmarmara" },
        { id: 686, province_id: 45, name: "Gördes", slug: "gordes" },
        { id: 687, province_id: 45, name: "Kırkağaç", slug: "kirakac" },
        { id: 688, province_id: 45, name: "Köprübaşı", slug: "koprubasi" },
        { id: 689, province_id: 45, name: "Kula", slug: "kula" },
        { id: 690, province_id: 45, name: "Salihli", slug: "salihli" },
        { id: 691, province_id: 45, name: "Sarıgöl", slug: "sarigol" },
        { id: 692, province_id: 45, name: "Saruhanlı", slug: "saruhanli" },
        { id: 693, province_id: 45, name: "Selendi", slug: "selendi" },
        { id: 694, province_id: 45, name: "Soma", slug: "soma" },
        { id: 695, province_id: 45, name: "Şehzadeler", slug: "sehzadeler" },
        { id: 696, province_id: 45, name: "Turgutlu", slug: "turgutlu" },
        { id: 697, province_id: 45, name: "Yunusemre", slug: "yunusemre" },

        // Mardin (47)
        { id: 698, province_id: 47, name: "Artuklu", slug: "artuklu" },
        { id: 699, province_id: 47, name: "Dargeçit", slug: "dargecit" },
        { id: 700, province_id: 47, name: "Derik", slug: "derik" },
        { id: 701, province_id: 47, name: "Kızıltepe", slug: "kiziltepe" },
        { id: 702, province_id: 47, name: "Mazıdağı", slug: "mazidagi" },
        { id: 703, province_id: 47, name: "Midyat", slug: "midyat" },
        { id: 704, province_id: 47, name: "Nusaybin", slug: "nusaybin" },
        { id: 705, province_id: 47, name: "Ömerli", slug: "omerli" },
        { id: 706, province_id: 47, name: "Savur", slug: "savur" },
        { id: 707, province_id: 47, name: "Yeşilli", slug: "yesilli" },

        // Mersin (33)
        { id: 708, province_id: 33, name: "Akdeniz", slug: "akdeniz" },
        { id: 709, province_id: 33, name: "Anamur", slug: "anamur" },
        { id: 710, province_id: 33, name: "Aydıncık", slug: "aydincik" },
        { id: 711, province_id: 33, name: "Bozyazı", slug: "bozyazi" },
        { id: 712, province_id: 33, name: "Çamlıyayla", slug: "camliyayla" },
        { id: 713, province_id: 33, name: "Erdemli", slug: "erdemli" },
        { id: 714, province_id: 33, name: "Gülnar", slug: "glunar" },
        { id: 715, province_id: 33, name: "Mezitli", slug: "mezitli" },
        { id: 716, province_id: 33, name: "Mut", slug: "mut" },
        { id: 717, province_id: 33, name: "Silifke", slug: "silifke" },
        { id: 718, province_id: 33, name: "Tarsus", slug: "tarsus" },
        { id: 719, province_id: 33, name: "Toroslar", slug: "toroslar" },
        { id: 720, province_id: 33, name: "Yenişehir", slug: "yenisehir" },

        // Muğla (48)
        { id: 721, province_id: 48, name: "Bodrum", slug: "bodrum" },
        { id: 722, province_id: 48, name: "Dalaman", slug: "dalaman" },
        { id: 723, province_id: 48, name: "Datça", slug: "datca" },
        { id: 724, province_id: 48, name: "Fethiye", slug: "fethiye" },
        { id: 725, province_id: 48, name: "Kavaklıdere", slug: "kavaklidere" },
        { id: 726, province_id: 48, name: "Köyceğiz", slug: "koycegi" },
        { id: 727, province_id: 48, name: "Marmaris", slug: "marmaris" },
        { id: 728, province_id: 48, name: "Menteşe", slug: "mentese" },
        { id: 729, province_id: 48, name: "Milas", slug: "milas" },
        { id: 730, province_id: 48, name: "Ortaca", slug: "ortaca" },
        { id: 731, province_id: 48, name: "Seydikemer", slug: "seydikemer" },
        { id: 732, province_id: 48, name: "Ula", slug: "ula" },
        { id: 733, province_id: 48, name: "Yatağan", slug: "yatagan" },

        // Muş (49)
        { id: 734, province_id: 49, name: "Bulanık", slug: "bulanik" },
        { id: 735, province_id: 49, name: "Hasköy", slug: "haskoy" },
        { id: 736, province_id: 49, name: "Korkut", slug: "korkut" },
        { id: 737, province_id: 49, name: "Malazgirt", slug: "malazgirt" },
        { id: 738, province_id: 49, name: "Merkez", slug: "merkez" },
        { id: 739, province_id: 49, name: "Varto", slug: "varto" },

        // Nevşehir (50)
        { id: 740, province_id: 50, name: "Acıgöl", slug: "acigol" },
        { id: 741, province_id: 50, name: "Avanos", slug: "avanos" },
        { id: 742, province_id: 50, name: "Derinkuyu", slug: "derinkuyu" },
        { id: 743, province_id: 50, name: "Gülşehir", slug: "gulsehir" },
        { id: 744, province_id: 50, name: "Hacıbektaş", slug: "hacibektas" },
        { id: 745, province_id: 50, name: "Kozaklı", slug: "kozakli" },
        { id: 746, province_id: 50, name: "Merkez", slug: "merkez" },
        { id: 747, province_id: 50, name: "Ürgüp", slug: "urgup" },

        // Niğde (51)
        { id: 748, province_id: 51, name: "Altunhisar", slug: "altunhisar" },
        { id: 749, province_id: 51, name: "Bor", slug: "bor" },
        { id: 750, province_id: 51, name: "Çamardı", slug: "camardı" },
        { id: 751, province_id: 51, name: "Çiftlik", slug: "ciftlik" },
        { id: 752, province_id: 51, name: "Merkez", slug: "merkez" },
        { id: 753, province_id: 51, name: "Ulukışla", slug: "ulukisla" },

        // Ordu (52)
        { id: 754, province_id: 52, name: "Akkuş", slug: "akkus" },
        { id: 755, province_id: 52, name: "Altınordu", slug: "altinordu" },
        { id: 756, province_id: 52, name: "Aybastı", slug: "aybasti" },
        { id: 757, province_id: 52, name: "Çamaş", slug: "camas" },
        { id: 758, province_id: 52, name: "Çatalpınar", slug: "catalpinar" },
        { id: 759, province_id: 52, name: "Çaybaşı", slug: "caybasi" },
        { id: 760, province_id: 52, name: "Fatsa", slug: "fatsa" },
        { id: 761, province_id: 52, name: "Gölköy", slug: "golkoy" },
        { id: 762, province_id: 52, name: "Gülyalı", slug: "gulali" },
        { id: 763, province_id: 52, name: "Gürgentepe", slug: "gurgentepe" },
        { id: 764, province_id: 52, name: "İkizce", slug: "ikizce" },
        { id: 765, province_id: 52, name: "Kabadüz", slug: "kabaduz" },
        { id: 766, province_id: 52, name: "Kabataş", slug: "kabatas" },
        { id: 767, province_id: 52, name: "Korgan", slug: "korgan" },
        { id: 768, province_id: 52, name: "Kumru", slug: "kumru" },
        { id: 769, province_id: 52, name: "Mesudiye", slug: "mesudiye" },
        { id: 770, province_id: 52, name: "Perşembe", slug: "persembe" },
        { id: 771, province_id: 52, name: "Ulubey", slug: "ulubey" },
        { id: 772, province_id: 52, name: "Ünye", slug: "unye" },

        // Osmaniye (80)
        { id: 773, province_id: 80, name: "Bahçe", slug: "bahce" },
        { id: 774, province_id: 80, name: "Düziçi", slug: "duzici" },
        { id: 775, province_id: 80, name: "Hasanbeyli", slug: "hasanbeyli" },
        { id: 776, province_id: 80, name: "Kadirli", slug: "kadirli" },
        { id: 777, province_id: 80, name: "Merkez", slug: "merkez" },
        { id: 778, province_id: 80, name: "Sumbas", slug: "sumbas" },
        { id: 779, province_id: 80, name: "Toprakkale", slug: "toprakka" },

        // Rize (53)
        { id: 780, province_id: 53, name: "Ardeşen", slug: "ardesen" },
        { id: 781, province_id: 53, name: "Çamlıhemşin", slug: "camlihemsin" },
        { id: 782, province_id: 53, name: "Çayeli", slug: "cayeli" },
        { id: 783, province_id: 53, name: "Derepazarı", slug: "derepazari" },
        { id: 784, province_id: 53, name: "Fındıklı", slug: "findikli" },
        { id: 785, province_id: 53, name: "Güneysu", slug: "gunesu" },
        { id: 786, province_id: 53, name: "Hemşin", slug: "hemsin" },
        { id: 787, province_id: 53, name: "İkizdere", slug: "ikizdere" },
        { id: 788, province_id: 53, name: "İyidere", slug: "iyidere" },
        { id: 789, province_id: 53, name: "Kalkandere", slug: "kalkandere" },
        { id: 790, province_id: 53, name: "Merkez", slug: "merkez" },
        { id: 791, province_id: 53, name: "Pazar", slug: "pazar" },

        // Sakarya (54)
        { id: 792, province_id: 54, name: "Adapazarı", slug: "adapazari" },
        { id: 793, province_id: 54, name: "Akyazı", slug: "akyazi" },
        { id: 794, province_id: 54, name: "Arifiye", slug: "arifiye" },
        { id: 795, province_id: 54, name: "Erenler", slug: "erenler" },
        { id: 796, province_id: 54, name: "Ferizli", slug: "ferizli" },
        { id: 797, province_id: 54, name: "Geyve", slug: "geyve" },
        { id: 798, province_id: 54, name: "Hendek", slug: "hendek" },
        { id: 799, province_id: 54, name: "Karapürçek", slug: "karapurcek" },
        { id: 800, province_id: 54, name: "Karasu", slug: "karasu" },
        { id: 801, province_id: 54, name: "Kaynarca", slug: "kaynarca" },
        { id: 802, province_id: 54, name: "Kocaali", slug: "kocaali" },
        { id: 803, province_id: 54, name: "Pamukova", slug: "pamukova" },
        { id: 804, province_id: 54, name: "Sapanca", slug: "sapanca" },
        { id: 805, province_id: 54, name: "Serdivan", slug: "serdivan" },
        { id: 806, province_id: 54, name: "Söğütlü", slug: "sogutlu" },
        { id: 807, province_id: 54, name: "Taraklı", slug: "tarakli" },

        // Samsun (55)
        { id: 808, province_id: 55, name: "19 Mayıs", slug: "19 mayis" },
        { id: 809, province_id: 55, name: "Alaçam", slug: "alacam" },
        { id: 810, province_id: 55, name: "Asarcık", slug: "asarcik" },
        { id: 811, province_id: 55, name: "Atakum", slug: "atakum" },
        { id: 812, province_id: 55, name: "Ayvacık", slug: "ayvacik" },
        { id: 813, province_id: 55, name: "Bafra", slug: "bafra" },
        { id: 814, province_id: 55, name: "Canik", slug: "canik" },
        { id: 815, province_id: 55, name: "Çarşamba", slug: "carsamba" },
        { id: 816, province_id: 55, name: "Havza", slug: "havza" },
        { id: 817, province_id: 55, name: "İlkadım", slug: "ilkadim" },
        { id: 818, province_id: 55, name: "Kavak", slug: "kavak" },
        { id: 819, province_id: 55, name: "Ladik", slug: "ladik" },
        { id: 820, province_id: 55, name: "Salıpazarı", slug: "salipazari" },
        { id: 821, province_id: 55, name: "Tekkeköy", slug: "tekkekoy" },
        { id: 822, province_id: 55, name: "Terme", slug: "terme" },
        { id: 823, province_id: 55, name: "Vezirköprü", slug: "vezirkopru" },
        { id: 824, province_id: 55, name: "Yakakent", slug: "yakakent" },

        // Siirt (56)
        { id: 825, province_id: 56, name: "Baykan", slug: "baykan" },
        { id: 826, province_id: 56, name: "Eruh", slug: "eruh" },
        { id: 827, province_id: 56, name: "Kurtalan", slug: "kurtalan" },
        { id: 828, province_id: 56, name: "Merkez", slug: "merkez" },
        { id: 829, province_id: 56, name: "Pervari", slug: "pervari" },
        { id: 830, province_id: 56, name: "Şirvan", slug: "sirvan" },
        { id: 831, province_id: 56, name: "Tillo", slug: "tillo" },

        // Sinop (57)
        { id: 832, province_id: 57, name: "Ayancık", slug: "ayancik" },
        { id: 833, province_id: 57, name: "Boyabat", slug: "boyabat" },
        { id: 834, province_id: 57, name: "Dikmen", slug: "dikmen" },
        { id: 835, province_id: 57, name: "Durağan", slug: "duragan" },
        { id: 836, province_id: 57, name: "Erfelek", slug: "erfelek" },
        { id: 837, province_id: 57, name: "Gerze", slug: "gerze" },
        { id: 838, province_id: 57, name: "Merkez", slug: "merkez" },
        { id: 839, province_id: 57, name: "Saraydüzü", slug: "sarayduzu" },
        { id: 840, province_id: 57, name: "Türkeli", slug: "turkeli" },

        // Sivas (58)
        { id: 841, province_id: 58, name: "Akıncılar", slug: "akincilar" },
        { id: 842, province_id: 58, name: "Altınyayla", slug: "altinyayla" },
        { id: 843, province_id: 58, name: "Divriği", slug: "divrig" },
        { id: 844, province_id: 58, name: "Doğanşar", slug: "dogansar" },
        { id: 845, province_id: 58, name: "Gemerek", slug: "gemerek" },
        { id: 846, province_id: 58, name: "Gölova", slug: "golova" },
        { id: 847, province_id: 58, name: "Gürün", slug: "gurun" },
        { id: 848, province_id: 58, name: "Hafik", slug: "hafik" },
        { id: 849, province_id: 58, name: "İmranlı", slug: "imranli" },
        { id: 850, province_id: 58, name: "Kangal", slug: "kangal" },
        { id: 851, province_id: 58, name: "Koyulhisar", slug: "koyulhisar" },
        { id: 852, province_id: 58, name: "Merkez", slug: "merkez" },
        { id: 853, province_id: 58, name: "Suşehri", slug: "susehri" },
        { id: 854, province_id: 58, name: "Şarkışla", slug: "sarkisla" },
        { id: 855, province_id: 58, name: "Ulaş", slug: "ulas" },
        { id: 856, province_id: 58, name: "Yıldızeli", slug: "yildizeli" },
        { id: 857, province_id: 58, name: "Zara", slug: "zara" },

        // Şanlıurfa (63)
        { id: 858, province_id: 63, name: "Akçakale", slug: "akcakale" },
        { id: 859, province_id: 63, name: "Birecik", slug: "birecik" },
        { id: 860, province_id: 63, name: "Bozova", slug: "bozova" },
        { id: 861, province_id: 63, name: "Ceylanpınar", slug: "ceylanpinar" },
        { id: 862, province_id: 63, name: "Eyyübiye", slug: "eyyubiye" },
        { id: 863, province_id: 63, name: "Halfeti", slug: "halfeti" },
        { id: 864, province_id: 63, name: "Haliliye", slug: "haliliye" },
        { id: 865, province_id: 63, name: "Harran", slug: "harran" },
        { id: 866, province_id: 63, name: "Hilvan", slug: "hilvan" },
        { id: 867, province_id: 63, name: "Karaköprü", slug: "karakopru" },
        { id: 868, province_id: 63, name: "Siverek", slug: "siverek" },
        { id: 869, province_id: 63, name: "Suruç", slug: "suruc" },
        { id: 870, province_id: 63, name: "Viranşehir", slug: "viransehir" },

        // Şırnak (73)
        { id: 871, province_id: 73, name: "Beytüşşebap", slug: "beytussebap" },
        { id: 872, province_id: 73, name: "Cizre", slug: "cizre" },
        { id: 873, province_id: 73, name: "Güçlükonak", slug: "guclukonak" },
        { id: 874, province_id: 73, name: "İdil", slug: "idil" },
        { id: 875, province_id: 73, name: "Merkez", slug: "merkez" },
        { id: 876, province_id: 73, name: "Silopi", slug: "silopi" },
        { id: 877, province_id: 73, name: "Uludere", slug: "uludere" },

        // Tekirdağ (59)
        { id: 878, province_id: 59, name: "Çerkezköy", slug: "cerkezkoy" },
        { id: 879, province_id: 59, name: "Çorlu", slug: "corlu" },
        { id: 880, province_id: 59, name: "Ergene", slug: "ergene" },
        { id: 881, province_id: 59, name: "Hayrabolu", slug: "hayrabolu" },
        { id: 882, province_id: 59, name: "Kapaklı", slug: "kapakli" },
        { id: 883, province_id: 59, name: "Malkara", slug: "malkara" },
        { id: 884, province_id: 59, name: "Marmaraereğlisi", slug: "marmaraereglisi" },
        { id: 885, province_id: 59, name: "Muratlı", slug: "muratli" },
        { id: 886, province_id: 59, name: "Saray", slug: "saray" },
        { id: 887, province_id: 59, name: "Süleymanpaşa", slug: "suleymanpasa" },
        { id: 888, province_id: 59, name: "Şarköy", slug: "sarkoy" },

        // Tokat (60)
        { id: 889, province_id: 60, name: "Almus", slug: "almus" },
        { id: 890, province_id: 60, name: "Artova", slug: "artova" },
        { id: 891, province_id: 60, name: "Başçiftlik", slug: "basciflik" },
        { id: 892, province_id: 60, name: "Erbaa", slug: "erbaa" },
        { id: 893, province_id: 60, name: "Merkez", slug: "merkez" },
        { id: 894, province_id: 60, name: "Niksar", slug: "niksar" },
        { id: 895, province_id: 60, name: "Pazar", slug: "pazar" },
        { id: 896, province_id: 60, name: "Reşadiye", slug: "resadiye" },
        { id: 897, province_id: 60, name: "Sulusaray", slug: "sulusaray" },
        { id: 898, province_id: 60, name: "Turhal", slug: "turhal" },
        { id: 899, province_id: 60, name: "Yeşilyurt", slug: "yesilyurt" },
        { id: 900, province_id: 60, name: "Zile", slug: "zile" },

        // Trabzon (61)
        { id: 901, province_id: 61, name: "Akçaabat", slug: "akcababat" },
        { id: 902, province_id: 61, name: "Araklı", slug: "arakli" },
        { id: 903, province_id: 61, name: "Arsin", slug: "arsin" },
        { id: 904, province_id: 61, name: "Beşikdüzü", slug: "besikduzu" },
        { id: 905, province_id: 61, name: "Çarşıbaşı", slug: "carsibasi" },
        { id: 906, province_id: 61, name: "Çaykara", slug: "caykara" },
        { id: 907, province_id: 61, name: "Dernekpazarı", slug: "dernekpazari" },
        { id: 908, province_id: 61, name: "Düzköy", slug: "duzkoy" },
        { id: 909, province_id: 61, name: "Hayrat", slug: "hayrat" },
        { id: 910, province_id: 61, name: "Köprübaşı", slug: "koprubasi" },
        { id: 911, province_id: 61, name: "Maçka", slug: "macka" },
        { id: 912, province_id: 61, name: "Of", slug: "of" },
        { id: 913, province_id: 61, name: "Ortahisar", slug: "ortahisar" },
        { id: 914, province_id: 61, name: "Sürmene", slug: "surmene" },
        { id: 915, province_id: 61, name: "Şalpazarı", slug: "salpazari" },
        { id: 916, province_id: 61, name: "Tonya", slug: "tonya" },
        { id: 917, province_id: 61, name: "Vakfıkebir", slug: "vakfikebir" },
        { id: 918, province_id: 61, name: "Yomra", slug: "yomra" },

        // Tunceli (62)
        { id: 919, province_id: 62, name: "Çemişgezek", slug: "cemisgezek" },
        { id: 920, province_id: 62, name: "Hozat", slug: "hozat" },
        { id: 921, province_id: 62, name: "Mazgirt", slug: "mazgirt" },
        { id: 922, province_id: 62, name: "Merkez", slug: "merkez" },
        { id: 923, province_id: 62, name: "Nazımiye", slug: "nazimiye" },
        { id: 924, province_id: 62, name: "Ovacık", slug: "ovacik" },
        { id: 925, province_id: 62, name: "Pertek", slug: "pertek" },
        { id: 926, province_id: 62, name: "Pülümür", slug: "pulumur" },

        // Uşak (64)
        { id: 927, province_id: 64, name: "Banaz", slug: "banaz" },
        { id: 928, province_id: 64, name: "Eşme", slug: "esme" },
        { id: 929, province_id: 64, name: "Karahallı", slug: "karahalli" },
        { id: 930, province_id: 64, name: "Merkez", slug: "merkez" },
        { id: 931, province_id: 64, name: "Sivaslı", slug: "sivasli" },
        { id: 932, province_id: 64, name: "Ulubey", slug: "ulubey" },

        // Van (65)
        { id: 933, province_id: 65, name: "Bahçesaray", slug: "bahcesaray" },
        { id: 934, province_id: 65, name: "Başkale", slug: "baskale" },
        { id: 935, province_id: 65, name: "Çaldıran", slug: "caldiran" },
        { id: 936, province_id: 65, name: "Çatak", slug: "catak" },
        { id: 937, province_id: 65, name: "Edremit", slug: "edremit" },
        { id: 938, province_id: 65, name: "Erciş", slug: "erci" },
        { id: 939, province_id: 65, name: "Gevaş", slug: "gevas" },
        { id: 940, province_id: 65, name: "Gürpınar", slug: "gurpinar" },
        { id: 941, province_id: 65, name: "İpekyolu", slug: "ipekyolu" },
        { id: 942, province_id: 65, name: "Muradiye", slug: "muradiye" },
        { id: 943, province_id: 65, name: "Özalp", slug: "ozalp" },
        { id: 944, province_id: 65, name: "Saray", slug: "saray" },
        { id: 945, province_id: 65, name: "Tuşba", slug: "tusba" },

        // Yalova (77)
        { id: 946, province_id: 77, name: "Altınova", slug: "altinova" },
        { id: 947, province_id: 77, name: "Armutlu", slug: "armutlu" },
        { id: 948, province_id: 77, name: "Çınarcık", slug: "cinarcik" },
        { id: 949, province_id: 77, name: "Çiftlikköy", slug: "ciflikkoy" },
        { id: 950, province_id: 77, name: "Merkez", slug: "merkez" },
        { id: 951, province_id: 77, name: "Termal", slug: "termal" },

        // Yozgat (66)
        { id: 952, province_id: 66, name: "Akdağmadeni", slug: "akdagmadeni" },
        { id: 953, province_id: 66, name: "Aydıncık", slug: "aydincik" },
        { id: 954, province_id: 66, name: "Boğazlıyan", slug: "bogazliyan" },
        { id: 955, province_id: 66, name: "Çandır", slug: "candir" },
        { id: 956, province_id: 66, name: "Çayıralan", slug: "cayiralan" },
        { id: 957, province_id: 66, name: "Çekerek", slug: "cekerek" },
        { id: 958, province_id: 66, name: "Kadışehri", slug: "kadisahri" },
        { id: 959, province_id: 66, name: "Merkez", slug: "merkez" },
        { id: 960, province_id: 66, name: "Saraykent", slug: "saraykent" },
        { id: 961, province_id: 66, name: "Sarıkaya", slug: "sarikaya" },
        { id: 962, province_id: 66, name: "Şefaatli", slug: "sefaatli" },
        { id: 963, province_id: 66, name: "Sorgun", slug: "sorgun" },
        { id: 964, province_id: 66, name: "Yenifakılı", slug: "yenifakili" },
        { id: 965, province_id: 66, name: "Yerköy", slug: "yerkoy" },

        // Zonguldak (67)
        { id: 966, province_id: 67, name: "Alaplı", slug: "alapli" },
        { id: 967, province_id: 67, name: "Çaycuma", slug: "caycuma" },
        { id: 968, province_id: 67, name: "Devrek", slug: "devrek" },
        { id: 969, province_id: 67, name: "Ereğli", slug: "eregli" },
        { id: 970, province_id: 67, name: "Gökçebey", slug: "gokcebey" },
        { id: 971, province_id: 67, name: "Kilimli", slug: "kilimli" },
        { id: 972, province_id: 67, name: "Kozlu", slug: "kozlu" },
        { id: 973, province_id: 67, name: "Merkez", slug: "merkez" }
    ]
};

export default turkiyeIlIlce;
